// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaa12GbRDOdHh1PlMWfKU3kI4C7XilESw',
    appId: '1:1081617952480:web:cdf777fc11000074f86a85',
    messagingSenderId: '1081617952480',
    projectId: 'halostories-84ff4',
    authDomain: 'halostories-84ff4.firebaseapp.com',
    storageBucket: 'halostories-84ff4.firebasestorage.app',
    measurementId: 'G-MYV2D9W1C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSYTuzI3_datyxhB26vtaLCuv-aijjlT0',
    appId: '1:1081617952480:android:5efa82057e6e96eaf86a85',
    messagingSenderId: '1081617952480',
    projectId: 'halostories-84ff4',
    storageBucket: 'halostories-84ff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzRax9nRCQhlCvZuA0-bO9-BmcF0yMGDw',
    appId: '1:1081617952480:ios:bbe6a8bdc6cde32cf86a85',
    messagingSenderId: '1081617952480',
    projectId: 'halostories-84ff4',
    storageBucket: 'halostories-84ff4.firebasestorage.app',
    iosBundleId: 'com.example.haloStories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzRax9nRCQhlCvZuA0-bO9-BmcF0yMGDw',
    appId: '1:1081617952480:ios:bbe6a8bdc6cde32cf86a85',
    messagingSenderId: '1081617952480',
    projectId: 'halostories-84ff4',
    storageBucket: 'halostories-84ff4.firebasestorage.app',
    iosBundleId: 'com.example.haloStories',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaa12GbRDOdHh1PlMWfKU3kI4C7XilESw',
    appId: '1:1081617952480:web:79e5316a2c59c159f86a85',
    messagingSenderId: '1081617952480',
    projectId: 'halostories-84ff4',
    authDomain: 'halostories-84ff4.firebaseapp.com',
    storageBucket: 'halostories-84ff4.firebasestorage.app',
    measurementId: 'G-3JC3JP8QQL',
  );
}
